### ISSUE TITLE
A few placeholders for the canned responses.

### ISSUE THREAD

**Issue by byparallax** [SajuukBot/SajuukBot#53]
### Hello hello, here is a little suggestion to make the bot's responses super fancy (Like that: ✨✨✨!).

The idea is to have a few **tags** and **sub-tags**. To avoid any issues, a tag must go with one sub-tag. So far the only tag I've though about is `{{user}}`, and here are his subtags: `id;   name;   discrim;   mention`. You could then build the following tag: `{{user.name}}`. To understand the feature better, here is an example:

```
❌ - Deleted a message from {{user.name}}#{{user.discrim}} ({{user.id}}) for the following reason: **Invite link**.
``` 
This snippet would then output:

❌ - Deleted a message from byParallax#0440 (231499325123854336) for the following reason: **Invite link**.

-----
*- byParallax#0440*

**Comment by byparallax** [comment]
Of course, you can always imagine a bunch of other tags and subtags. Throwing a few idea: **{{channel}}*, **{{guild}}**, ...

**Comment by SuperSajuuk** [comment]
Closing since this is something that I'll probably never implement.
